import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./redux/provider";
// @ts-ignore
import "materialize-css/dist/css/materialize.min.css";
import UserContext from "./user-context/userContext";
import Header from "./components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContext>
          <Providers>
            <Header />
            <div className="container">{children}</div>
          </Providers>
        </UserContext>
      </body>
    </html>
  );
}
